# Generated by Django 6.0.1 on 2026-05-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_region_branch_status_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='daily_target',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
