# Generated by Django 6.0.1 on 2026-05-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='daily_page_target',
            field=models.PositiveIntegerField(default=100, help_text='Daily Page Target'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='daily_target',
            field=models.PositiveIntegerField(default=20, help_text='Daily File Target'),
        ),
    ]
