# Generated by Django 6.0.1 on 2026-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branch_daily_page_target_alter_branch_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='total_target',
            field=models.PositiveIntegerField(default=600, help_text='Total Project Target'),
        ),
    ]
