# Generated by Django 6.0.1 on 2026-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_target', models.PositiveIntegerField(default=50000)),
                ('daily_target_per_branch', models.PositiveIntegerField(default=20)),
                ('backup_frequency', models.CharField(default='Daily', max_length=50)),
                ('alert_threshold_days', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
