# Generated by Django 6.0.1 on 2026-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworksubmission',
            name='pages_scanned_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
