# Generated by Django 6.0.1 on 2026-05-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_dailyworksubmission_pages_scanned_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworksubmission',
            name='problems_encountered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyworksubmission',
            name='solutions_taken',
            field=models.TextField(blank=True),
        ),
    ]
