# Generated by Django 6.0.1 on 2026-05-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_dailyworksubmission_problems_encountered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
